---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ivoandco/public_html/
    - /bin/cp * $DEPLOYPATH
    - /bin/cp /email-api/contact.php $DEPLOYPATH
    - /bin/cp /email-api/error_log $DEPLOYPATH
    - /bin/cp /icons/* $DEPLOYPATH
    